title: Labelbox Tracking
description: A site to download daily tracking data.
baseurl: ""
url: "https://dollysods.github.io/labelbox-tracking"
theme: minima
exclude:
  - tracking_data/
include:
  - assets/tracking_data/
