name: Automate Reports Workflow

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: [main]

jobs:
  generate-and-process-reports:
    runs-on: ubuntu-latest
    env:
      LABELBOX_API_KEY: ${{ secrets.LABELBOX_API_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install python-dotenv pandas requests msal labelbox

      - name: Debug Secrets Presence
        run: |
          if [ -z "$LABELBOX_API_KEY" ]; then
            echo "LABELBOX_API_KEY is missing!"
            exit 1
          else
            echo "LABELBOX_API_KEY is set."
          fi
          if [ -z "$PERSONAL_ACCESS_TOKEN" ]; then
            echo "PERSONAL_ACCESS_TOKEN is missing!"
            exit 1
          else
            echo "PERSONAL_ACCESS_TOKEN is set."
          fi

      - name: Run tracking_export.py
        run: python tracking_export.py

      - name: Run labelbox-tracking-txt.py
        run: python labelbox-tracking-txt.py

      - name: Run labelbox-tracking-csv.py
        run: python labelbox-tracking-csv.py

      - name: Commit and Push Outputs
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/tailored-ai/labelbox-tracking.git
          git remote -v  # Debugging: Check remote URL
          git add exports/*.ndjson exports/*.csv tracking_data/*.txt tracking_data/*.csv
          git commit -m "Automated Export and Report Generation: $(date)" || echo "No changes to commit"
          git push origin main
