name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Step 2: Copy Tracking Data to Assets Directory
      - name: Copy Tracking Data
        run: |
          # Clear out the old files
          rm -rf assets/tracking_data/*
          mkdir -p assets/tracking_data
      
          echo "Contents of tracking_data before copy:"
          ls -la tracking_data || echo "tracking_data directory is empty"
      
          # Copy the latest files
          cp tracking_data/*.csv assets/tracking_data/ || echo "No CSV files found"
          cp tracking_data/*.txt assets/tracking_data/ || echo "No TXT files found"
      
          # Retain only the latest files in assets directory
          LATEST_CSV=$(ls -t tracking_data/*.csv | head -n 1 | xargs -n 1 basename)
          LATEST_TXT=$(ls -t tracking_data/*.txt | head -n 1 | xargs -n 1 basename)
      
          echo "Removing older files from assets directory..."
          find assets/tracking_data -type f ! -name "${LATEST_CSV}" ! -name "${LATEST_TXT}" -delete
      
          echo "Contents of assets/tracking_data after cleanup:"
          ls -la assets/tracking_data


      # Step 3: Update index.md with the Latest Files
      - name: Update Index with Latest Files
        run: |
          LATEST_CSV=$(ls -t assets/tracking_data/*.csv 2>/dev/null | head -n 1 | xargs -n 1 basename || echo "No CSV file found")
          LATEST_TXT=$(ls -t assets/tracking_data/*.txt 2>/dev/null | head -n 1 | xargs -n 1 basename || echo "No TXT file found")
      
          echo "---" > index.md
          echo "layout: default" >> index.md
          echo "title: Tracking Data" >> index.md
          echo "---" >> index.md
          echo "" >> index.md
          echo "# Daily Tracking Reports" >> index.md
          echo "" >> index.md
          echo "Download the latest tracking data below:" >> index.md
          echo "" >> index.md
          echo "- [CSV Report](/assets/tracking_data/${LATEST_CSV})" >> index.md
          echo "- [TXT Report](/assets/tracking_data/${LATEST_TXT})" >> index.md

      # Step 4: Debug Updated Index
      - name: Debug Updated Index
        run: |
          echo "Contents of index.md:"
          cat index.md

      # Step 5: Build with Jekyll
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      # Step 6: Debug Jekyll Build Output
      - name: Debug Jekyll Build Output
        run: |
          echo "Contents of the build output directory (_site):"
          ls -la _site/assets/tracking_data || echo "assets/tracking_data not found in _site"

      # Step 7: Upload Artifact for Deployment
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
