name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Tracking Data Directory
        run: |
          echo "Checking tracking_data directory:"
          ls -la tracking_data || echo "tracking_data directory does not exist"

      - name: Copy Tracking Data
        run: |
          mkdir -p assets/tracking_data
          cp tracking_data/*.csv assets/tracking_data/ || echo "No CSV files found"
          cp tracking_data/*.txt assets/tracking_data/ || echo "No TXT files found"
        working-directory: .

      - name: Debug Assets Directory
        run: |
          echo "Contents of assets/tracking_data:"
          ls -la assets/tracking_data || echo "assets/tracking_data directory not created"

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Debug Build Output
  
