name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Prepare Files for GitHub Pages
        run: |
          mkdir -p docs/tracking_data
          cp tracking_data/*.csv docs/tracking_data/
          cp tracking_data/*.txt docs/tracking_data/
          echo "Files prepared for GitHub Pages deployment"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
